apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
namePrefix: az-
commonLabels:
  location_code: AZ
patchesStrategicMerge:
- |-
  apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: cups-restart
  spec:
    schedule: "*/10 * * * *"
