apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: greetings
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: cron-test
              image: "alpine:latest"
              args:
                - Hello
              command:
                - echo
            restartPolicy: OnFailure
