apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cups-restart
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cups-restart-cronjob
            image: bitnami/kubectl
            command:
              - 'kubectl'
              - 'delete'
              - 'pods'
              - '--selector=app=guestbook-ui'
              - '-n default'
          restartPolicy: OnFailure
