---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: cups-restart
rules:
- apiGroups:
  - extensions
  - apps
  resources:
  - pods
  verbs:
  - get
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cups-restart
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-cups-restart
  namespace: default
roleRef:
  kind: Role
  name: cups-restart
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cups-restart
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cups-restart
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-cups-restart
          containers:
          - name: cups-restart-cronjob
            image: bitnami/kubectl
            command:
              - 'kubectl'
              - 'delete'
              - 'pods'
              - '--selector=app=guestbook-ui'
              - '-n default'
          restartPolicy: OnFailure
