apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
namePrefix: ca-
commonLabels:
  location_code: CA
patchesStrategicMerge:
- |-
  apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: cups-restart
  spec:
    schedule: "*/10 * * * *"