apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../base
namePrefix: nj-
commonLabels:
  location_code: NJ
patchesStrategicMerge:
- |-
  apiVersion: batch/v1
  kind: CronJob
  metadata:
    name: cups-restart
  spec:
    schedule: "*/5 * * * *"