---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cups-restart
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cups-restart
subjects:
- kind: ServiceAccount
  name: sa-cups-restart
roleRef:
  kind: Role
  name: cups-restart
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cups-restart
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cups-restart
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: sa-cups-restart
          containers:
          - name: cups-restart-cronjob
            image: bitnami/kubectl
            env:
              - name: HOOK_URL
                valueFrom:
                  secretKeyRef:
                    name: slack-notification-url
                    key: argocd
              - name: LOCATION_CODE
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.labels['location_code']
            command: ["/bin/sh","-c"]
            args: ["kubectl delete pods -l app=nginx,location_code=$(LOCATION_CODE); curl -X POST --data-urlencode payload={\"channel\": \"#somechannel\", \"username\": \"hello\", \"text\": \"Restarted cups at $(LOCATION_CODE)\", \"icon_emoji\": \":ghost:\"} $(HOOK_URL)"]
          restartPolicy: Never

