---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: cups-restart
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cups-restart
  namespace: default
subjects:
- kind: ServiceAccount
  name: sa-cups-restart
  namespace: default
roleRef:
  kind: Role
  name: cups-restart
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-cups-restart
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cups-restart
spec:
  schedule: "*/1 * * * *"
  backoffLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: sa-cups-restart
          containers:
          - name: cups-restart-cronjob
            image: bitnami/kubectl
            command:
              - 'kubectl'
              - 'delete'
              - 'pods'
              - '-l'
              - 'app=nginx,location_code=${LOCATION_CODE}'
          restartPolicy: Never
