apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- guestbook-ui-deployment.yaml
- guestbook-ui-svc.yaml
- guestbook-nginx-statefulset.yaml
- guestbook-cronjob.yaml